package com.sati.model;
// Generated 28 nov. 2021 à 14:09:32 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre", catalog = "pneuma_bd")
public class Genre implements java.io.Serializable {

	private int idGenre;
	private Integer codeGenre;
	private String libelleGenre;
	private Set<Personne> personnes = new HashSet<Personne>(0);

	public Genre() {
	}

	public Genre(int idGenre) {
		this.idGenre = idGenre;
	}

	public Genre(int idGenre, Integer codeGenre, String libelleGenre, Set<Personne> personnes) {
		this.idGenre = idGenre;
		this.codeGenre = codeGenre;
		this.libelleGenre = libelleGenre;
		this.personnes = personnes;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_GENRE", unique = true, nullable = false)
	public int getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(int idGenre) {
		this.idGenre = idGenre;
	}
	
	@Column(name = "CODE_GENRE")
	public Integer getCodeGenre() {
		return this.codeGenre;
	}

	public void setCodeGenre(Integer codeGenre) {
		this.codeGenre = codeGenre;
	}

	@Column(name = "LIBELLE_GENRE", length = 10)
	public String getLibelleGenre() {
		return this.libelleGenre;
	}

	public void setLibelleGenre(String libelleGenre) {
		this.libelleGenre = libelleGenre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Personne> getPersonnes() {
		return this.personnes;
	}

	public void setPersonnes(Set<Personne> personnes) {
		this.personnes = personnes;
	}

}
