package com.sati.model;
// Generated 28 nov. 2021 à 14:09:32 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name = "personne", catalog = "pneuma_bd")
public class Personne implements java.io.Serializable {

	private int idPers;
	private Genre genre;
	private String numeroPers;
	private String nomPers;
	private String prenomsPers;
	private Date dateNais;
	private String lieuNais;
	private String teephonePers;
	private String EMailPers;
	private Set<Audition> auditions = new HashSet<Audition>(0);

	public Personne() {
	}

	public Personne(int idPers, Genre genre) {
		this.idPers = idPers;
		this.genre = genre;
	}

	public Personne(int idPers, Genre genre, String numeroPers, String nomPers, String prenomsPers, Date dateNais,
			String lieuNais, String teephonePers, String EMailPers, Set<Audition> auditions) {
		this.idPers = idPers;
		this.genre = genre;
		this.numeroPers = numeroPers;
		this.nomPers = nomPers;
		this.prenomsPers = prenomsPers;
		this.dateNais = dateNais;
		this.lieuNais = lieuNais;
		this.teephonePers = teephonePers;
		this.EMailPers = EMailPers;
		this.auditions = auditions;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_PERS", unique = true, nullable = false)
	public int getIdPers() {
		return this.idPers;
	}

	public void setIdPers(int idPers) {
		this.idPers = idPers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GENRE", nullable = false)
	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	@Column(name = "NUMERO_PERS", length = 20)
	public String getNumeroPers() {
		return this.numeroPers;
	}

	public void setNumeroPers(String numeroPers) {
		this.numeroPers = numeroPers;
	}

	@Column(name = "NOM_PERS", length = 25)
	public String getNomPers() {
		return this.nomPers;
	}

	public void setNomPers(String nomPers) {
		this.nomPers = nomPers;
	}

	@Column(name = "PRENOMS_PERS", length = 50)
	public String getPrenomsPers() {
		return this.prenomsPers;
	}

	public void setPrenomsPers(String prenomsPers) {
		this.prenomsPers = prenomsPers;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAIS", length = 10)
	public Date getDateNais() {
		return this.dateNais;
	}

	public void setDateNais(Date dateNais) {
		this.dateNais = dateNais;
	}

	@Column(name = "LIEU_NAIS", length = 50)
	public String getLieuNais() {
		return this.lieuNais;
	}

	public void setLieuNais(String lieuNais) {
		this.lieuNais = lieuNais;
	}

	@Column(name = "TEEPHONE_PERS", length = 10)
	public String getTeephonePers() {
		return this.teephonePers;
	}

	public void setTeephonePers(String teephonePers) {
		this.teephonePers = teephonePers;
	}

	@Column(name = "E_MAIL_PERS", length = 60)
	public String getEMailPers() {
		return this.EMailPers;
	}

	public void setEMailPers(String EMailPers) {
		this.EMailPers = EMailPers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personne")
	public Set<Audition> getAuditions() {
		return this.auditions;
	}

	public void setAuditions(Set<Audition> auditions) {
		this.auditions = auditions;
	}

}
