package com.sati.model;
// Generated 28 nov. 2021 à 14:09:32 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "pneuma_bd")
public class Question implements java.io.Serializable {

	private int idQest;
	private Integer codeQuest;
	private Integer numeroQuest;
	private String libelleQuest;
	private Set<Audition> auditions = new HashSet<Audition>(0);

	public Question() {
	}

	public Question(int idQest) {
		this.idQest = idQest;
	}

	public Question(int idQest, Integer codeQuest, Integer numeroQuest, String libelleQuest, Set<Audition> auditions) {
		this.idQest = idQest;
		this.codeQuest = codeQuest;
		this.numeroQuest = numeroQuest;
		this.libelleQuest = libelleQuest;
		this.auditions = auditions;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_QEST", unique = true, nullable = false)
	public int getIdQest() {
		return this.idQest;
	}

	public void setIdQest(int idQest) {
		this.idQest = idQest;
	}

	@Column(name = "CODE_QUEST")
	public Integer getCodeQuest() {
		return this.codeQuest;
	}

	public void setCodeQuest(Integer codeQuest) {
		this.codeQuest = codeQuest;
	}

	@Column(name = "NUMERO_QUEST")
	public Integer getNumeroQuest() {
		return this.numeroQuest;
	}

	public void setNumeroQuest(Integer numeroQuest) {
		this.numeroQuest = numeroQuest;
	}

	@Column(name = "LIBELLE_QUEST", length = 200)
	public String getLibelleQuest() {
		return this.libelleQuest;
	}

	public void setLibelleQuest(String libelleQuest) {
		this.libelleQuest = libelleQuest;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<Audition> getAuditions() {
		return this.auditions;
	}

	public void setAuditions(Set<Audition> auditions) {
		this.auditions = auditions;
	}

}
