package com.sati.model;
// Generated 28 nov. 2021 à 14:09:32 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Reponse generated by hbm2java
 */
@Entity
@Table(name = "reponse", catalog = "pneuma_bd")
public class Reponse implements java.io.Serializable {

	private int idRep;
	private Integer valeur;
	private Integer numeroRep;
	private String libelleRep;
	private Set<Audition> auditions = new HashSet<Audition>(0);

	public Reponse() {
	}

	public Reponse(int idRep) {
		this.idRep = idRep;
	}

	public Reponse(int idRep, Integer valeur, Integer numeroRep, String libelleRep, Set<Audition> auditions) {
		this.idRep = idRep;
		this.valeur = valeur;
		this.numeroRep = numeroRep;
		this.libelleRep = libelleRep;
		this.auditions = auditions;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_REP", unique = true, nullable = false)
	public int getIdRep() {
		return this.idRep;
	}

	public void setIdRep(int idRep) {
		this.idRep = idRep;
	}

	@Column(name = "VALEUR")
	public Integer getValeur() {
		return this.valeur;
	}

	public void setValeur(Integer valeur) {
		this.valeur = valeur;
	}

	@Column(name = "NUMERO_REP")
	public Integer getNumeroRep() {
		return this.numeroRep;
	}

	public void setNumeroRep(Integer numeroRep) {
		this.numeroRep = numeroRep;
	}

	@Column(name = "LIBELLE_REP", length = 20)
	public String getLibelleRep() {
		return this.libelleRep;
	}

	public void setLibelleRep(String libelleRep) {
		this.libelleRep = libelleRep;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "reponse")
	public Set<Audition> getAuditions() {
		return this.auditions;
	}

	public void setAuditions(Set<Audition> auditions) {
		this.auditions = auditions;
	}

}
