package com.sati.model;
// Generated 13 sept. 2019 18:13:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * UserAuthentication generated by hbm2java
 */
@Entity
@Table(name = "user_authentication", catalog = "pneuma_bd")
public class UserAuthentication implements java.io.Serializable {

	private int userId;
	private String username;
	private String password;
	private Boolean enabled;
	private String nomUser;
	private String prenomsUser;
	private Set<UserAuthorization> userAuthorizations = new HashSet<UserAuthorization>(0);

	public UserAuthentication() {
	}

	public UserAuthentication(int userId) {
		this.userId = userId;
	}

	public UserAuthentication(int userId, String username, String password, Boolean enabled,
			String nomUser, String prenomsUser, Set<UserAuthorization> userAuthorizations) {
		this.userId = userId;
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.nomUser = nomUser;
		this.prenomsUser = prenomsUser;
		this.userAuthorizations = userAuthorizations;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "USER_ID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}


	@Column(name = "USERNAME", length = 15)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ENABLED")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}


	@Column(name = "NOM_USER", length = 25)
	public String getNomUser() {
		return this.nomUser;
	}

	public void setNomUser(String nomUser) {
		this.nomUser = nomUser;
	}

	@Column(name = "PRENOMS_USER", length = 50)
	public String getPrenomsUser() {
		return this.prenomsUser;
	}

	public void setPrenomsUser(String prenomsUser) {
		this.prenomsUser = prenomsUser;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAuthentication")
	public Set<UserAuthorization> getUserAuthorizations() {
		return this.userAuthorizations;
	}

	public void setUserAuthorizations(Set<UserAuthorization> userAuthorizations) {
		this.userAuthorizations = userAuthorizations;
	}

}
