package com.sati.model;
// Generated 13 sept. 2019 18:13:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * UserAuthorization generated by hbm2java
 */
@Entity
@Table(name = "user_authorization", catalog = "pneuma_bd")
public class UserAuthorization implements java.io.Serializable {

	private int userRoleId;
	private UserAuthentication userAuthentication;
	private String role;

	public UserAuthorization() {
	}

	public UserAuthorization(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserAuthorization(int userRoleId, UserAuthentication userAuthentication, String role) {
		this.userRoleId = userRoleId;
		this.userAuthentication = userAuthentication;
		this.role = role;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "USER_ROLE_ID", unique = true, nullable = false)
	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public UserAuthentication getUserAuthentication() {
		return this.userAuthentication;
	}

	public void setUserAuthentication(UserAuthentication userAuthentication) {
		this.userAuthentication = userAuthentication;
	}

	@Column(name = "ROLE", length = 20)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
